//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleApp.Lookup {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IconData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IconData() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleApp.Lookup.IconData", typeof(IconData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M10.5 6C7.468 6 5 8.468 5 11.5L5 36C5 39.309 7.691 42 11 42L22.605469 42C22.858469 41.042 23.225516 39.759 23.728516 38L11 38C9.897 38 9 37.103 9 36L9 16L39 16L39 22.521484C39.427 22.340484 39.8615 22.188422 40.3125 22.107422C40.7065 22.036422 41.102859 21.992953 41.505859 22.001953C42.015859 22.001953 42.515 22.067641 43 22.181641L43 11.5C43 8.468 40.532 6 37.5 6L10.5 6 z M 13.5 20 A 1.50015 1.50015 0 1 0 13.5 23L15.5 23 A 1.50015 1.50015 0 1 0 15.5 20L13.5 20 z M 21.5 20C20.672 20 20 20.671 20 21.5C20 22. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string AgendaIcon {
            get {
                return ResourceManager.GetString("AgendaIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M12.03125 2.0625C11.710938 2.066406 11.355469 2.207031 11.03125 2.53125L4.4375 9L1 9C0.449219 9 0 9.449219 0 10L0 16C0 16.550781 0.449219 17 1 17L4.4375 17L11 23.4375C12 24.4375 13 23.925781 13 22.5625L13 3.28125C13 2.488281 12.566406 2.058594 12.03125 2.0625 Z M 19.28125 3.0625C18.84375 3.136719 18.507813 3.492188 18.457031 3.933594C18.410156 4.375 18.652344 4.796875 19.0625 4.96875C22 6.449219 24 9.476563 24 13C24 16.523438 22 19.550781 19.0625 21.03125C18.695313 21.15625 18.4375 21.484375 18.394531 21.86 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string AudioIcon {
            get {
                return ResourceManager.GetString("AudioIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M8 3C7.449219 3 7 3.449219 7 4L7 30C7 30.554688 7.449219 31 8 31L13 31C13.554688 31 14 30.554688 14 30L14 4C14 3.449219 13.554688 3 13 3 Z M 17 3C16.449219 3 16 3.449219 16 4L16 30C16 30.554688 16.449219 31 17 31L22 31C22.554688 31 23 30.554688 23 30L23 4C23 3.449219 22.554688 3 22 3 Z M 9.5 7L11.5 7C12.054688 7 12.5 7.449219 12.5 8C12.5 8.550781 12.054688 9 11.5 9L9.5 9C8.945313 9 8.5 8.550781 8.5 8C8.5 7.449219 8.945313 7 9.5 7 Z M 18.5 7L20.5 7C21.054688 7 21.5 7.449219 21.5 8C21.5 8.550781 21.054688 9 2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string BookIcon {
            get {
                return ResourceManager.GetString("BookIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M8.2246094 1L7.8554688 2.0800781L7.8515625 2.09375L7.8417969 2.1152344L2.40625 17.679688L1.5839844 20L30.416016 20L29.943359 18.666016L29.59375 17.679688L25.089844 4.8046875L24.833984 4.6210938C23.095769 3.36838 21.825769 2.4447394 20.083984 1.1894531L19.822266 1L8.2246094 1 z M 9.7695312 2.6621094L9.7558594 2.7050781L9.65625 3L19.177734 3C20.68328 4.0858412 21.900734 4.9719311 23.410156 6.0605469L27.585938 18L4.4121094 18L9.7148438 2.8183594L9.6777344 2.90625C9.7139884 2.827358 9.7451424 2.7454366 9.769531 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string icon {
            get {
                return ResourceManager.GetString("icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M17,3h2c0.386,0,0.738,0.223,0.904,0.572s0.115,0.762-0.13,1.062L11.292,15l8.482,10.367 c0.245,0.299,0.295,0.712,0.13,1.062S19.386,27,19,27h-2c-0.3,0-0.584-0.135-0.774-0.367l-9-11c-0.301-0.369-0.301-0.898,0-1.267 l9-11C16.416,3.135,16.7,3,17,3z.
        /// </summary>
        internal static string leftArrow {
            get {
                return ResourceManager.GetString("leftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M15 3C13.895 3 13 3.895 13 5L13 5.2929688C10.109011 6.1538292 8 8.8293311 8 12L8 14.757812C8 17.474812 6.921 20.079 5 22 A 1 1 0 0 0 4 23 A 1 1 0 0 0 5 24L25 24 A 1 1 0 0 0 26 23 A 1 1 0 0 0 25 22C23.079 20.079 22 17.474812 22 14.757812L22 12C22 8.8293311 19.890989 6.1538292 17 5.2929688L17 5C17 3.895 16.105 3 15 3 z M 3.9550781 7.9882812 A 1.0001 1.0001 0 0 0 3.1054688 8.5527344C3.1054688 8.5527344 2 10.666667 2 13C2 15.333333 3.1054687 17.447266 3.1054688 17.447266 A 1.0001165 1.0001165 0 0 0 4.8945312 16 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NotifIcon {
            get {
                return ResourceManager.GetString("NotifIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M12,27h-2c-0.386,0-0.738-0.223-0.904-0.572s-0.115-0.762,0.13-1.062L17.708,15L9.226,4.633 c-0.245-0.299-0.295-0.712-0.13-1.062S9.614,3,10,3h2c0.3,0,0.584,0.135,0.774,0.367l9,11c0.301,0.369,0.301,0.898,0,1.267l-9,11 C12.584,26.865,12.3,27,12,27z.
        /// </summary>
        internal static string rightArrow {
            get {
                return ResourceManager.GetString("rightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M17.78125 0.1875L16.28125 0.8125L16.6875 2.6875C16.3125 2.960938 16.003906 3.304688 15.71875 3.6875L13.8125 3.25L13.1875 4.75L14.8125 5.78125C14.738281 6.25 14.746094 6.722656 14.8125 7.1875L13.1875 8.21875L13.78125 9.71875L15.6875 9.3125C15.960938 9.683594 16.304688 9.996094 16.6875 10.28125L16.21875 12.1875L17.71875 12.8125L18.78125 11.15625C19.25 11.226563 19.730469 11.226563 20.1875 11.15625L21.21875 12.8125L22.71875 12.21875L22.28125 10.3125C22.652344 10.039063 22.96875 9.691406 23.25 9.3125L25.1875 9. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SettingIcon {
            get {
                return ResourceManager.GetString("SettingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M4 1L4 19C7.398438 19 10 18.304688 12 19.90625L12 2.8125C10 1.011719 7.398438 1 4 1 Z M 22 1C18.601563 1 16 1.011719 14 2.8125L14 19.90625C16 18.304688 18.601563 19 22 19 Z M 1 4C0.398438 4 0 4.398438 0 5L0 23C0 23.601563 0.398438 24 1 24L9.09375 24C10.09375 24 11.398438 25.90625 13 25.90625C14.601563 25.90625 15.90625 24 16.90625 24L25 24C25.601563 24 26 23.601563 26 23L26 5C26 4.398438 25.601563 4 25 4L24 4L24 19C24 20.5 23.5 21 22 21L17.6875 21C15.988281 21 15.289063 21.09375 14.6875 22.09375C14.289063 2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SymbolIcon {
            get {
                return ResourceManager.GetString("SymbolIcon", resourceCulture);
            }
        }
    }
}
