//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleApp.Lookup {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IconData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IconData() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleApp.Lookup.IconData", typeof(IconData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M10.5 6C7.468 6 5 8.468 5 11.5L5 36C5 39.309 7.691 42 11 42L22.605469 42C22.858469 41.042 23.225516 39.759 23.728516 38L11 38C9.897 38 9 37.103 9 36L9 16L39 16L39 22.521484C39.427 22.340484 39.8615 22.188422 40.3125 22.107422C40.7065 22.036422 41.102859 21.992953 41.505859 22.001953C42.015859 22.001953 42.515 22.067641 43 22.181641L43 11.5C43 8.468 40.532 6 37.5 6L10.5 6 z M 13.5 20 A 1.50015 1.50015 0 1 0 13.5 23L15.5 23 A 1.50015 1.50015 0 1 0 15.5 20L13.5 20 z M 21.5 20C20.672 20 20 20.671 20 21.5C20 22. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string AgendaIcon {
            get {
                return ResourceManager.GetString("AgendaIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M0 2L0 4L26 4L26 2 Z M 0 7L0 9L26 9L26 7 Z M 0 12L0 14L26 14L26 12 Z M 0 17L0 19L26 19L26 17 Z M 0 22L0 24L26 24L26 22Z.
        /// </summary>
        internal static string Align_justify_icon {
            get {
                return ResourceManager.GetString("Align_justify_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M0 1L0 3L24 3L24 1 Z M 0 6L0 8L16 8L16 6 Z M 0 11L0 13L24 13L24 11 Z M 0 16L0 18L16 18L16 16 Z M 0 21L0 23L24 23L24 21Z.
        /// </summary>
        internal static string Align_left_icon {
            get {
                return ResourceManager.GetString("Align_left_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M0 2L0 4L26 4L26 2 Z M 8 7L8 9L26 9L26 7 Z M 0 12L0 14L26 14L26 12 Z M 8 17L8 19L26 19L26 17 Z M 0 22L0 24L26 24L26 22Z.
        /// </summary>
        internal static string Align_right_icon {
            get {
                return ResourceManager.GetString("Align_right_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M254.15,234.1V13.5c0-7.5-6-13.5-13.5-13.5s-13.5,6-13.5,13.5v220.6c-31.3,6.3-55,34-55,67.2s23.7,60.9,55,67.2v98.2
        ///			c0,7.5,6,13.5,13.5,13.5s13.5-6,13.5-13.5v-98.2c31.3-6.3,55-34,55-67.2C309.15,268.2,285.55,240.4,254.15,234.1z M240.65,342.8
        ///			c-22.9,0-41.5-18.6-41.5-41.5s18.6-41.5,41.5-41.5s41.5,18.6,41.5,41.5S263.55,342.8,240.65,342.8z
        ///			M88.85,120.9V13.5c0-7.5-6-13.5-13.5-13.5s-13.5,6-13.5,13.5v107.4c-31.3,6.3-55,34-55,67.2s23.7,60.9,55,67.2v211.4
        ///			c0,7.5,6,13.5,13.5,13.5s13.5-6,13.5-13.5V255.2c31. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string AppSettingIcon {
            get {
                return ResourceManager.GetString("AppSettingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M25 2C23.894531 2 23 2.894531 23 4L23 7.210938C21.433594 6.199219 19.53125 4.785156 17.21875 4.25C16.316406 4.039063 15.40625 3.980469 14.519531 4C13.636719 4.019531 12.78125 4.117188 11.980469 4.210938C11.265625 4.300781 10.613281 4.371094 10.019531 4.417969L10 4.375L9.980469 4.421875C9.253906 4.476563 8.628906 4.492188 8.226563 4.398438C7.6875 4.273438 7.152344 4.609375 7.023438 5.144531C6.898438 5.683594 7.234375 6.222656 7.773438 6.347656C8.214844 6.449219 8.671875 6.476563 9.132813 6.480469L1.921875 23 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string AssiduityIcon {
            get {
                return ResourceManager.GetString("AssiduityIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M12.03125 2.0625C11.710938 2.066406 11.355469 2.207031 11.03125 2.53125L4.4375 9L1 9C0.449219 9 0 9.449219 0 10L0 16C0 16.550781 0.449219 17 1 17L4.4375 17L11 23.4375C12 24.4375 13 23.925781 13 22.5625L13 3.28125C13 2.488281 12.566406 2.058594 12.03125 2.0625 Z M 19.28125 3.0625C18.84375 3.136719 18.507813 3.492188 18.457031 3.933594C18.410156 4.375 18.652344 4.796875 19.0625 4.96875C22 6.449219 24 9.476563 24 13C24 16.523438 22 19.550781 19.0625 21.03125C18.695313 21.15625 18.4375 21.484375 18.394531 21.86 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string AudioIcon {
            get {
                return ResourceManager.GetString("AudioIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M8 3C7.449219 3 7 3.449219 7 4L7 30C7 30.554688 7.449219 31 8 31L13 31C13.554688 31 14 30.554688 14 30L14 4C14 3.449219 13.554688 3 13 3 Z M 17 3C16.449219 3 16 3.449219 16 4L16 30C16 30.554688 16.449219 31 17 31L22 31C22.554688 31 23 30.554688 23 30L23 4C23 3.449219 22.554688 3 22 3 Z M 9.5 7L11.5 7C12.054688 7 12.5 7.449219 12.5 8C12.5 8.550781 12.054688 9 11.5 9L9.5 9C8.945313 9 8.5 8.550781 8.5 8C8.5 7.449219 8.945313 7 9.5 7 Z M 18.5 7L20.5 7C21.054688 7 21.5 7.449219 21.5 8C21.5 8.550781 21.054688 9 2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string BookIcon {
            get {
                return ResourceManager.GetString("BookIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z.
        /// </summary>
        internal static string CloseIcon {
            get {
                return ResourceManager.GetString("CloseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M15.39,14.56C13.71,13.7,11.53,13,9,13c-2.53,0-4.71,0.7-6.39,1.56C1.61,15.07,1,16.1,1,17.22V20h16v-2.78 C17,16.1,16.39,15.07,15.39,14.56z M9,12c2.21,0,4-1.79,4-4c0-2.21-1.79-4-4-4S5,5.79,5,8C5,10.21,6.79,12,9,12z M20,9V6h-2v3h-3v2 h3v3h2v-3h3V9H20z.
        /// </summary>
        internal static string CreatePersonIcon {
            get {
                return ResourceManager.GetString("CreatePersonIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M19 5v2h-4V5h4M9 5v6H5V5h4m10 8v6h-4v-6h4M9 17v2H5v-2h4M21 3h-8v6h8V3zM11 3H3v10h8V3zm10 8h-8v10h8V11zm-10 4H3v6h8v-6z.
        /// </summary>
        internal static string DashboardIcon {
            get {
                return ResourceManager.GetString("DashboardIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M434.2,101.4h-13.762l5.229-30.72c0-1.707,0-4.267-1.707-5.973c-1.707-1.707-3.413-3.413-5.973-3.413l-64.628-10.44
        ///				L348.867,6.68C348.013,2.413,343.747-1,339.48-1L167.96,13.507c-2.56,0.853-4.267,1.707-5.973,3.413
        ///				c-0.853,1.707-1.707,3.413-1.707,5.973l4.305,39.463L82.627,78.36c-4.267,0.853-7.68,5.12-6.827,9.387l2.438,13.653H75.8
        ///				c-14.507,0-25.6,11.093-25.6,25.6v34.133c0,13.95,10.261,24.739,23.948,25.546l35.785,300.427
        ///				C110.787,500.76,121.88,511,135.533,511h238.933c12.8,0,24.747-10.24,25.6-23. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string DeletePersonIcon {
            get {
                return ResourceManager.GetString("DeletePersonIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M13 10C11.35503 10 10 11.35503 10 13L10 67C10 68.64497 11.35503 70 13 70L67 70C68.64497 70 70 68.64497 70 67L70 13C70 11.35503 68.64497 10 67 10L13 10 z M 13 12L39 12 A 1 1 0 0 0 40 13 A 1 1 0 0 0 41 12L67 12C67.56503 12 68 12.43497 68 13L68 67C68 67.56503 67.56503 68 67 68L41 68 A 1 1 0 0 0 40 67 A 1 1 0 0 0 39 68L13 68C12.43497 68 12 67.56503 12 67L12 13C12 12.43497 12.43497 12 13 12 z M 40 15 A 1 1 0 0 0 39 16 A 1 1 0 0 0 40 17 A 1 1 0 0 0 41 16 A 1 1 0 0 0 40 15 z M 40 19 A 1 1 0 0 0 39 20 A 1 1 0 0 0 4 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string DoubleColumnsIcon {
            get {
                return ResourceManager.GetString("DoubleColumnsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M475.65,63.5v-7.7c0-30.8-25-55.8-55.8-55.8s-55.8,25-55.8,55.8v7.7H475.65z
        ///			M345.55,439.5H39.25c-13.9,0-25.2,11.3-25.2,25.2l0,0c0,13.9,11.3,25.2,25.2,25.2h340.9L345.55,439.5z
        ///			M331.45,137.3H39.25c-13.9,0-25.2,11.3-25.2,25.2l0,0c0,13.9,11.3,25.2,25.2,25.2h292.2V137.3z
        ///				M331.45,238H39.25c-13.9,0-25.2,11.3-25.2,25.2l0,0c0,13.9,11.3,25.2,25.2,25.2h292.2V238z 
        ///				M331.45,338.7H39.25c-13.9,0-25.2,11.3-25.2,25.2l0,0c0,13.9,11.3,25.2,25.2,25.2h292.2V338.7z 
        ///				M364.15,96.2v312.9l50.8,73.4c2.4,3.5,7.6,3 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string EditIcon {
            get {
                return ResourceManager.GetString("EditIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M13.09375 4.78125L7.90625 11.375L6 9.6875L3.34375 12.6875L6.84375 15.8125L8.4375 17.21875L9.75 15.53125L16.25 7.21875 Z M 19 9L19 13L46 13L46 9 Z M 13.09375 18.78125L7.90625 25.375L6 23.6875L3.34375 26.6875L6.84375 29.8125L8.4375 31.21875L9.75 29.53125L16.25 21.21875 Z M 19 23L19 27L46 27L46 23 Z M 13.09375 32.78125L7.90625 39.375L6 37.6875L3.34375 40.6875L6.84375 43.8125L8.4375 45.21875L9.75 43.53125L16.25 35.21875 Z M 19 37L19 41L46 41L46 37Z.
        /// </summary>
        internal static string ExamIcon {
            get {
                return ResourceManager.GetString("ExamIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M25.162,3H16v2.984h3.031v2.031H16V10h3v2h-3v2h3v2h-3v2h3v2h-3v3h9.162
        ///		C25.623,23,26,22.609,26,22.13V3.87C26,3.391,25.623,3,25.162,3z M24,20h-4v-2h4V20z M24,16h-4v-2h4V16z M24,12h-4v-2h4V12z M24,8
        ///		h-4V6h4V8z M0,2.889v20.223L15,26V0L0,2.889z M9.488,18.08l-1.745-3.299c-0.066-0.123-0.134-0.349-0.205-0.678
        ///		H7.511C7.478,14.258,7.4,14.494,7.277,14.81l-1.751,3.27H2.807l3.228-5.064L3.082,7.951h2.776l1.448,3.037
        ///		c0.113,0.24,0.214,0.525,0.304,0.854h0.028c0.057-0.198,0.163-0.492,0.318-0.883l1.61-3.009h2.542 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ExcelIcon {
            get {
                return ResourceManager.GetString("ExcelIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M2 3L2 7L48 7L48 3 Z M 2 13L2 17L31 17L31 13 Z M 36.90625 14C36.808594 14.007813 36.71875 14.023438 36.625 14.0625C36.25 14.21875 36 14.597656 36 15L36 35C36 35.402344 36.25 35.785156 36.625 35.9375C36.75 35.988281 36.871094 36 37 36C37.261719 36 37.527344 35.910156 37.71875 35.71875L47.71875 25.71875C48.109375 25.328125 48.109375 24.671875 47.71875 24.28125L37.71875 14.28125C37.503906 14.066406 37.199219 13.972656 36.90625 14 Z M 2 23L2 27L31 27L31 23 Z M 2 33L2 37L31 37L31 33 Z M 2 43L2 47L48 47L48 43Z.
        /// </summary>
        internal static string ExpandMenuIcon {
            get {
                return ResourceManager.GetString("ExpandMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M11.07,12.85c0.77-1.39,2.25-2.21,3.11-3.44c0.91-1.29,0.4-3.7-2.18-3.7c-1.69,0-2.52,1.28-2.87,2.34L6.54,6.96 C7.25,4.83,9.18,3,11.99,3c2.35,0,3.96,1.07,4.78,2.41c0.7,1.15,1.11,3.3,0.03,4.9c-1.2,1.77-2.35,2.31-2.97,3.45 c-0.25,0.46-0.35,0.76-0.35,2.24h-2.89C10.58,15.22,10.46,13.95,11.07,12.85z M14,20c0,1.1-0.9,2-2,2s-2-0.9-2-2c0-1.1,0.9-2,2-2 S14,18.9,14,20z.
        /// </summary>
        internal static string HelpIcon {
            get {
                return ResourceManager.GetString("HelpIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M18.21875 0.125L17.53125 0.78125L4.03125 13.28125L4 13.28125C3.652344 13.628906 3.40625 14.136719 3.40625 14.65625C3.40625 14.917969 3.457031 15.179688 3.5625 15.40625L1 21.90625C0.898438 22.207031 0.988281 22.488281 1.1875 22.6875C1.386719 22.886719 1.792969 23 2.09375 23L8.5625 20.46875C8.824219 20.613281 9.128906 20.6875 9.4375 20.6875C9.957031 20.6875 10.464844 20.441406 10.8125 20.09375L10.84375 20.0625L23.25 6.46875L23.875 5.78125L23.21875 5.09375L18.90625 0.78125 Z M 18.15625 2.875L21.125 5.84375L13. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Highlight_icon {
            get {
                return ResourceManager.GetString("Highlight_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M8.2246094 1L7.8554688 2.0800781L7.8515625 2.09375L7.8417969 2.1152344L2.40625 17.679688L1.5839844 20L30.416016 20L29.943359 18.666016L29.59375 17.679688L25.089844 4.8046875L24.833984 4.6210938C23.095769 3.36838 21.825769 2.4447394 20.083984 1.1894531L19.822266 1L8.2246094 1 z M 9.7695312 2.6621094L9.7558594 2.7050781L9.65625 3L19.177734 3C20.68328 4.0858412 21.900734 4.9719311 23.410156 6.0605469L27.585938 18L4.4121094 18L9.7148438 2.8183594L9.6777344 2.90625C9.7139884 2.827358 9.7451424 2.7454366 9.769531 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string icon {
            get {
                return ResourceManager.GetString("icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M17,3h2c0.386,0,0.738,0.223,0.904,0.572s0.115,0.762-0.13,1.062L11.292,15l8.482,10.367 c0.245,0.299,0.295,0.712,0.13,1.062S19.386,27,19,27h-2c-0.3,0-0.584-0.135-0.774-0.367l-9-11c-0.301-0.369-0.301-0.898,0-1.267 l9-11C16.416,3.135,16.7,3,17,3z.
        /// </summary>
        internal static string leftArrow {
            get {
                return ResourceManager.GetString("leftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M6 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm12 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm-6 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z.
        /// </summary>
        internal static string MoreHoriIcon {
            get {
                return ResourceManager.GetString("MoreHoriIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z.
        /// </summary>
        internal static string MoreVertIcon {
            get {
                return ResourceManager.GetString("MoreVertIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M4 4L4 46L35.414062 46L46 35.414062L46 35L46 4L4 4 z M 6 6L44 6L44 34L34 34L34 44L6 44L6 6 z M 14 15L14 17L37 17L37 15L14 15 z M 14 21L14 23L37 23L37 21L14 21 z M 14 27L14 29L37 29L37 27L14 27 z M 36 36L42.585938 36L36 42.585938L36 36 z.
        /// </summary>
        internal static string Note_icon {
            get {
                return ResourceManager.GetString("Note_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M32.51,27.83A14.4,14.4,0,0,1,30,24.9a12.63,12.63,0,0,1-1.35-4.81V15.15A10.81,10.81,0,0,0,19.21,4.4V3.11a1.33,1.33,0,1,0-2.67,0V4.42A10.81,10.81,0,0,0,7.21,15.15v4.94A12.63,12.63,0,0,1,5.86,24.9a14.4,14.4,0,0,1-2.47,2.93,1,1,0,0,0-.34.75v1.36a1,1,0,0,0,1,1h27.8a1,1,0,0,0,1-1V28.58A1,1,0,0,0,32.51,27.83ZM5.13,28.94a16.17,16.17,0,0,0,2.44-3,14.24,14.24,0,0,0,1.65-5.85V15.15a8.74,8.74,0,1,1,17.47,0v4.94a14.24,14.24,0,0,0,1.65,5.85,16.17,16.17,0,0,0,2.44,3Z M18,34.28A2.67,2.67,0,0,0,20.58,32H15.32A2.67,2.67,0,0, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NotificationIcon {
            get {
                return ResourceManager.GetString("NotificationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M15 3C13.895 3 13 3.895 13 5L13 5.2929688C10.109011 6.1538292 8 8.8293311 8 12L8 14.757812C8 17.474812 6.921 20.079 5 22 A 1 1 0 0 0 4 23 A 1 1 0 0 0 5 24L25 24 A 1 1 0 0 0 26 23 A 1 1 0 0 0 25 22C23.079 20.079 22 17.474812 22 14.757812L22 12C22 8.8293311 19.890989 6.1538292 17 5.2929688L17 5C17 3.895 16.105 3 15 3 z M 3.9550781 7.9882812 A 1.0001 1.0001 0 0 0 3.1054688 8.5527344C3.1054688 8.5527344 2 10.666667 2 13C2 15.333333 3.1054687 17.447266 3.1054688 17.447266 A 1.0001165 1.0001165 0 0 0 4.8945312 16 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NotifIcon {
            get {
                return ResourceManager.GetString("NotifIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M19 8h-1V3H6v5H5c-1.66 0-3 1.34-3 3v6h4v4h12v-4h4v-6c0-1.66-1.34-3-3-3zM8 5h8v3H8V5zm8 12v2H8v-4h8v2zm2-2v-2H6v2H4v-4c0-.55.45-1 1-1h14c.55 0 1 .45 1 1v4h-2z.
        /// </summary>
        internal static string PrintIcon {
            get {
                return ResourceManager.GetString("PrintIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M12,27h-2c-0.386,0-0.738-0.223-0.904-0.572s-0.115-0.762,0.13-1.062L17.708,15L9.226,4.633 c-0.245-0.299-0.295-0.712-0.13-1.062S9.614,3,10,3h2c0.3,0,0.584,0.135,0.774,0.367l9,11c0.301,0.369,0.301,0.898,0,1.267l-9,11 C12.584,26.865,12.3,27,12,27z.
        /// </summary>
        internal static string rightArrow {
            get {
                return ResourceManager.GetString("rightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M17.78125 0.1875L16.28125 0.8125L16.6875 2.6875C16.3125 2.960938 16.003906 3.304688 15.71875 3.6875L13.8125 3.25L13.1875 4.75L14.8125 5.78125C14.738281 6.25 14.746094 6.722656 14.8125 7.1875L13.1875 8.21875L13.78125 9.71875L15.6875 9.3125C15.960938 9.683594 16.304688 9.996094 16.6875 10.28125L16.21875 12.1875L17.71875 12.8125L18.78125 11.15625C19.25 11.226563 19.730469 11.226563 20.1875 11.15625L21.21875 12.8125L22.71875 12.21875L22.28125 10.3125C22.652344 10.039063 22.96875 9.691406 23.25 9.3125L25.1875 9. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SettingIcon {
            get {
                return ResourceManager.GetString("SettingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M510.39,197.385l-4.777-17.826c-3.23-12.066-10.937-22.142-21.702-28.376c-10.755-6.233-23.312-7.894-35.314-4.673
        ///			l-16.533,4.427c-8.171-13.722-17.898-26.401-29.017-37.834l8.553-14.809c6.197-10.737,7.834-23.276,4.595-35.309
        ///			c-3.248-12.034-10.974-22.093-21.756-28.321l-15.987-9.226c-10.81-6.239-23.385-7.921-35.405-4.718
        ///			c-12.02,3.203-22.057,10.895-28.28,21.669l-8.544,14.809c-15.46-3.911-31.301-5.991-47.27-6.205l-4.44-16.538
        ///			C247.87,9.672,222.238-5.046,197.388,1.606l-17.825,4.772c-24.859,6.666-39.6 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SettingIcon1 {
            get {
                return ResourceManager.GetString("SettingIcon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M14 10C11.802666 10 10 11.802666 10 14L10 66C10 68.197334 11.802666 70 14 70L66 70C68.197334 70 70 68.197334 70 66L70 14C70 11.802666 68.197334 10 66 10L14 10 z M 14 12L66 12C67.116666 12 68 12.883334 68 14L68 66C68 67.116666 67.116666 68 66 68L14 68C12.883334 68 12 67.116666 12 66L12 14C12 12.883334 12.883334 12 14 12 z M 18 17 A 1 1 0 0 0 17 18 A 1 1 0 0 0 18 19 A 1 1 0 0 0 19 18 A 1 1 0 0 0 18 17 z M 22 17 A 1 1 0 0 0 21 18 A 1 1 0 0 0 22 19 A 1 1 0 0 0 23 18 A 1 1 0 0 0 22 17 z M 26 17 A 1 1 0 0 0 25 18 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SimpleColumnIcon {
            get {
                return ResourceManager.GetString("SimpleColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M24,13l2.9,5.9l0.9,1.9l2.1,0.3l6.5,0.9l-4.7,4.6l-1.5,1.5l0.4,2.1l1.1,6.5l-5.8-3.1l-1.9-1l-1.9,1l-5.8,3.1l1.1-6.5l0.4-2.1l-1.5-1.5l-4.7-4.6l6.5-0.9l2.1-0.3l0.9-1.9L24,13 M24,4l-6.5,13.2L3,19.3l10.5,10.2L11,44l13-6.8L37,44l-2.5-14.5L45,19.3l-14.5-2.1L24,4L24,4z.
        /// </summary>
        internal static string StarBorder_icon {
            get {
                return ResourceManager.GetString("StarBorder_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M24.913,5.186l5.478,12.288l13.378,1.413c0.861,0.091,1.207,1.158,0.564,1.737l-9.993,9.005l2.791,13.161c0.18,0.847-0.728,1.506-1.478,1.074L24,37.141l-11.653,6.722c-0.75,0.432-1.657-0.227-1.478-1.074l2.791-13.161l-9.993-9.005c-0.643-0.579-0.296-1.646,0.564-1.737l13.378-1.413l5.478-12.288C23.439,4.395,24.561,4.395,24.913,5.186z.
        /// </summary>
        internal static string StarFill_icon {
            get {
                return ResourceManager.GetString("StarFill_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M16.5 0C13.472656 0 11 2.472656 11 5.5C11 8.527344 13.472656 11 16.5 11C19.527344 11 22 8.527344 22 5.5C22 2.472656 19.527344 0 16.5 0 Z M 16.5 2C18.445313 2 20 3.554688 20 5.5C20 7.445313 18.445313 9 16.5 9C14.554688 9 13 7.445313 13 5.5C13 3.554688 14.554688 2 16.5 2 Z M 6.15625 9.78125C5.003906 9.742188 3.941406 10.550781 3.5625 11.6875C3.550781 11.699219 3.542969 11.707031 3.53125 11.71875L0.28125 22.65625L0.25 22.65625C0.242188 22.675781 0.257813 22.699219 0.25 22.71875C-0.0078125 23.476563 0.00390625  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string StudentIcon {
            get {
                return ResourceManager.GetString("StudentIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M4 1L4 19C7.398438 19 10 18.304688 12 19.90625L12 2.8125C10 1.011719 7.398438 1 4 1 Z M 22 1C18.601563 1 16 1.011719 14 2.8125L14 19.90625C16 18.304688 18.601563 19 22 19 Z M 1 4C0.398438 4 0 4.398438 0 5L0 23C0 23.601563 0.398438 24 1 24L9.09375 24C10.09375 24 11.398438 25.90625 13 25.90625C14.601563 25.90625 15.90625 24 16.90625 24L25 24C25.601563 24 26 23.601563 26 23L26 5C26 4.398438 25.601563 4 25 4L24 4L24 19C24 20.5 23.5 21 22 21L17.6875 21C15.988281 21 15.289063 21.09375 14.6875 22.09375C14.289063 2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SymbolIcon {
            get {
                return ResourceManager.GetString("SymbolIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M4 5L4 7L45 7L45 39L19 39L19 41L46 41C46.56503 41 47 41.43497 47 42L47 43L19 43L19 45L48 45 A 1.0001 1.0001 0 0 0 49 44L49 42C49 40.743378 48.106694 39.85942 47 39.416016L47 6 A 1.0001 1.0001 0 0 0 46 5L4 5 z M 9 11C5.1458495 11 2 14.145852 2 18C2 21.854148 5.1458495 25 9 25C12.854151 25 16 21.854148 16 18C16 14.145852 12.854151 11 9 11 z M 20 11L20 13L21 13L31 13L32 13L32 11L31 11L21 11L20 11 z M 35 11L35 13L36 13L41 13L42 13L42 11L41 11L36 11L35 11 z M 9 13C11.773271 13 14 15.226731 14 18C14 20.773269 11. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TeacherIcon {
            get {
                return ResourceManager.GetString("TeacherIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M13 11C10.802666 11 9 12.802666 9 15L9 65C9 67.197334 10.802666 69 13 69L67 69C69.197334 69 71 67.197334 71 65L71 15C71 12.802666 69.197334 11 67 11L13 11 z M 13 13L67 13C68.116666 13 69 13.883334 69 15L69 65C69 66.116666 68.116666 67 67 67L13 67C11.883334 67 11 66.116666 11 65L11 15C11 13.883334 11.883334 13 13 13 z M 30 15 A 1 1 0 0 0 29 16 A 1 1 0 0 0 30 17 A 1 1 0 0 0 31 16 A 1 1 0 0 0 30 15 z M 50 15 A 1 1 0 0 0 49 16 A 1 1 0 0 0 50 17 A 1 1 0 0 0 51 16 A 1 1 0 0 0 50 15 z M 30 19 A 1 1 0 0 0 29 20 A 1 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TripleColumnsIcon {
            get {
                return ResourceManager.GetString("TripleColumnsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M101.869,299.627c-24.669,0-46.986,15.544-55.534,38.683c-2.04,5.526,0.785,11.663,6.312,13.705
        ///				c1.219,0.45,2.468,0.663,3.697,0.663c4.338,0,8.417-2.667,10.008-6.974c5.466-14.796,19.739-24.739,35.517-24.739
        ///				c5.892,0,10.669-4.779,10.669-10.669C112.538,304.402,107.763,299.627,101.869,299.627z 
        ///				M256.001,250.426c-21.975,0-39.853,17.879-39.853,39.854c0,21.974,17.878,39.851,39.853,39.851
        ///				c21.975,0,39.852-17.877,39.852-39.851C295.853,268.304,277.976,250.426,256.001,250.426z M256.001,308.793
        ///				c- [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ViewIcon {
            get {
                return ResourceManager.GetString("ViewIcon", resourceCulture);
            }
        }
    }
}
